Update gcloudsdk.nuspec
gpoul/chocolatey-packages pull request #5
Opened 2020-10-22 16:54 UTC by ronca71

Added python3 dependency

2020-10-23 15:18 UTC, IvanaGyro requested changes
The version of 20200527 has not been released before, so we can stay in `0.0.0.20200527` to make the version consistent to the signing time of the executable installer.

I tested this package in [Chocolatey Testing Environment](https://github.com/chocolatey-community/chocolatey-test-environment). It is successfully installed when I tested with the inline provisioner, but I got exit code 2 when I tested with running the command in the box. I had to reopen the shell (or enter `refreshenv`) and to run the install command again to make the installation procees successful. This situation may relate to https://github.com/chocolatey/choco/issues/439. But it seems that the issue was solved years ago. Does we have to concern the user may get exit code 2 if they install this package with the command line without python3 preinstalled?

2020-10-23 15:18 UTC, IvanaGyro commented on gcloudsdk/gcloudsdk.nuspec
> ++    </dependencies>
Here are some redundant '+' signs.
```suggestion
       <dependency id="python3" />
       <dependency id="chocolatey-core.extension" version="1.1.0" />
     </dependencies>
```

2020-10-25 18:25 UTC, ronca71 commented
I suppose "chocolatey-core.extension" dependency is useless. Verified package installation in the Choco Test Env without it and all was completed succesfully.

2020-10-26 02:23 UTC, IvanaGyro commented
> 
> 
> I suppose "chocolatey-core.extension" dependency is useless. Verified package installation in the Choco Test Env without it and all was completed succesfully.

Yes. chocolatey-core.extension is not necessary. Would you remove it before merging?

2020-11-08 19:10 UTC, ronca71 commented
- removed choco core extension as dependency
- aligned version to 20200527
- added a comment in chocolateyinstall.ps1 to warn about Python 3.x required, though I expect users should never run PS script manually

2020-11-09 02:45 UTC, IvanaGyro commented on gcloudsdk/gcloudsdk.nuspec
> +    <version>0.0.0.20205027</version>
```suggestion
    <version>0.0.0.202005027</version>
```
Missed a zero.

2020-11-09 02:47 UTC, IvanaGyro commented on gcloudsdk/gcloudsdk.nuspec
> +    <version>0.0.0.20205027</version>
```suggestion
    <version>0.0.0.20200527</version>
```
Here is a typo.

2020-11-11 01:50 UTC, IvanaGyro approved these changes

2020-11-11 01:55 UTC, IvanaGyro commented
@gpoul Could you grant us permission to merge PR?

2020-11-11 08:02 UTC, merged